# Workflow name
name: "Chromatic"

# Event for the workflow
on: push

# List of jobs
jobs:
chromatic-deployment:
# Operating System
runs-on: ubuntu-latest
# Job steps
steps:
uses: actions/checkout@v1
name: Install dependencies
#
4 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, pm, p
run: yarn
# 4 Adds Chromatic as a step in the workflow
name: Publish to Chijomatic
uses: chromaui/action@v1
# Chromatic GitHub Action options
with:
#
4 Chromatic projectToken, refer to the manage page to obtain it.
projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
